### ISSUE TITLE
搜索时正在播放的音乐会无限卡顿

### ISSUE THREAD

**Issue by HuangLiang0927** [algerkong/AlgerMusicPlayer#15]
### 重现链接

GIF

### 重现步骤

RT  搜索时正在播放的音乐会无限卡顿
![卡顿](https://github.com/user-attachments/assets/04c341d1-4de4-45b8-bc08-3e068f6d1f7c)

### 期望结果

请修复

**Comment by HuangLiang0927** [comment]
输入法是 微信输入法

**Comment by HuangLiang0927** [comment]
安装的版本是  AlgerMusic_2.1.0_Setup_x64

**Comment by algerkong** [comment]
好的，我看看
